### ISSUE TITLE
After initial setup no environments populate to connect to

### ISSUE THREAD

**Issue by ZXColt** [iann0036/cloud9-sync#2]
I am using AWS Cloud9 to collaborate with a few other devs on a Linux server. After I put in my credentials with the AWS access key and secret key and region nothing in the environments populate. I can create a new environment and it will show up on my AWS Cloud9 environment list.

**Comment by iann0036** [comment]
Hey Colton,

Thanks for raising. I'll put in a fix for your issue in the next release. The problem is simply that the environment list isn't refreshing properly, so you should be able to manually hit the refresh button or restart VS Code for now.

Please be aware that the editor sync is currently unstable and so you might find the live editing features aren't very usable in a production capacity. Regardless, try it out and let me know if you have further feedback.

**Comment by ZXColt** [comment]
>Hey Colton, ...

@iann0036 I tried restarting VS Code and refreshing with the button as well to no avail. I will give it a try after your changes. I will keep you posted on anything else I might encounter. I like the concept here and will gladly keep testing it during its development.

**Comment by mike-mosher** [comment]
+1.  Having the same issue.

**Comment by iann0036** [comment]
Could you please try to update to the latest version (0.9.0) and try again?

If it still doesn't work, could you post the logs you see in Help > Toggle Developer Tools > "Console" tab? (please remove any identifying information if present)

**Comment by ZXColt** [comment]
Issue seemed to be resolved for me. Thanks.
